name: targetdiff
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - ipykernel=6
  - matplotlib=3.8
  - palettable=3.3
  - numpy=1.23
  - tqdm=4.65
  - einops=0.7
  - pytorch-cuda=12.1
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - lightning=2.2
  - wandb=0.16
  - diffusers=0.21
  - pyg::pyg=2.5
  - pyg::pytorch-sparse=0.6
  - pyg::pytorch-scatter=2.1
  - pyg::pytorch-cluster=1.6
  - rdkit=2022.03.2
  - openbabel=3.1.1
  - tensorboard=2.16
  - pyyaml=6
  - easydict=1.9
  - python-lmdb=1.4
  - scipy=1.12
  - pdb2pqr=3.6
  - vina=1.2.2
  - jsonpickle=3.0
  - cma=3.3.0
  - transformers=4.35.2
  - sentencepiece=0.1.99
  - pip:
    - jsonargparse[signatures]==4.27.7
    - git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3.git@aee55d50d5bdcfdbcd80220499df8cde2a8f4b2a
    - meeko==0.1.dev3
    - unicodeitplus==0.3.1
    # - git+https://github.com/uber-research/TuRBO.git