name: vina-webapp
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - ipykernel=6
  - uvicorn=0.27
  - fastapi=0.109
  - jsonpickle=3.0
  - numpy=1.23
  - tqdm=4.65
  - rdkit=2022.03.2
  - openbabel=3.1.1
  - pyyaml=6
  - easydict=1.9
  - python-lmdb=1.4
  - scipy=1.12
  - python-multipart
  - pdb2pqr=3.6
  - vina=1.2.2